#!/bin/bash

echo "=== MySQL Kurulum Talimatları ==="
echo ""
echo "1. MySQL kurulumu (Ubuntu/Debian):"
echo "   sudo apt update"
echo "   sudo apt install mysql-server"
echo ""
echo "2. MySQL'i başlat:"
echo "   sudo systemctl start mysql"
echo "   sudo systemctl enable mysql"
echo ""
echo "3. MySQL'e root olarak giriş yap:"
echo "   sudo mysql"
echo ""
echo "4. Veritabanı ve kullanıcı oluştur:"
echo "   CREATE DATABASE kolajai;"
echo "   CREATE USER 'kolajai'@'localhost' IDENTIFIED BY 'kolajai123';"
echo "   GRANT ALL PRIVILEGES ON kolajai.* TO 'kolajai'@'localhost';"
echo "   FLUSH PRIVILEGES;"
echo "   EXIT;"
echo ""
echo "5. Config dosyasını güncelle (config.yaml):"
echo "   database:"
echo "     host: localhost"
echo "     port: 3306"
echo "     name: kolajai"
echo "     user: kolajai"
echo "     password: kolajai123"
echo ""
echo "6. Uygulamayı çalıştır:"
echo "   make build"
echo "   ./dist/kolajai-marketplace"
echo ""
echo "=== Alternatif: Docker Kullanımı ==="
echo ""
echo "Eğer Docker kuruluysa:"
echo "   docker-compose -f docker-compose-dev.yml up -d"
echo ""